### ISSUE TITLE
not working on chrome anymore

### ISSUE THREAD

**Issue by kingktm** [mr-yt12/lichess-gui-use-code-example#28]
this extension is not working anymore. Is this the problem of browser or lichess itself? I am pretty used to this but now I feel sad.  Can someone fix this problem please.

**Comment by randomguyreborn** [comment]
@mr-yt12 Can you assign this to me?

**Comment by randomguyreborn** [comment]
@kingktm @mr-yt12 will be fixed by https://github.com/mr-yt12/lichess-gui-use-code-example/pull/33

**Comment by randomguyreborn** [comment]
@kingktm Fixed!
