### ISSUE TITLE
I cant install the extention.

### ISSUE THREAD

**Issue by IPlayChes** [mr-yt12/lichess-gui-use-code-example#35]
I cant install the extention. Please help.

Also, it worked before and now it got uninstalled.

PS I'm on a chromebook.

**Comment by randomguyreborn** [comment]
@IPlayChes Currently The extension is no longer supported

**Comment by Inf4ge** [comment]
remove line 1653 in code.js to test: [for testing only](https://github.com/mr-yt12/lichess-gui-use-code-example/archive/074e3a8c14089dc1d591bfffdaed08e5a1637777.zip)

**Comment by randomguyreborn** [comment]
> remove line 1653 in code.js to test: [for testing only](https://github.com/mr-yt12/lichess-gui-use-code-example/archive/074e3a8c14089dc1d591bfffdaed08e5a1637777.zip)

**I guess you won't be able to play with it without modifying the extension cuz if you start a game you will be redirected to https://lichess.org/page/play-extensions see this change in lichess https://github.com/ornicar/lila/commit/121bfc76ce69e3994e4ab7a870bf5478da0ee7a4**

**Comment by Inf4ge** [comment]
agreed, lichess's ToS have recently been changed

**Comment by mr-yt12** [comment]
This version works on mskchess.ru: 
https://chrome.google.com/webstore/detail/mskchess-keyboard-input/beaekfhgnpkeaemddboeojhljnjoebfl
